# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: forbid-crlf
        stages: [commit]
      - id: remove-crlf
        stages: [commit]
      - id: forbid-tabs
        stages: [commit]
      - id: remove-tabs
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-added-large-files
        stages: [commit]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        stages: [commit]
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa
        name: nbqa-autoflake
        stages: [commit]
        args:
          - autoflake
          - --in-place
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
        additional_dependencies:
          - autoflake
      - id: nbqa-isort
        stages: [commit]
        args:
          - --profile=black
          - --line-length=120
      - id: nbqa-black
        stages: [commit]
        args:
          - --line-length=120
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
